### ISSUE TITLE
[Operation Not permitted While starting GVM Container] [Bug]

### ISSUE THREAD

**Issue by imad777550** [Secure-Compliance-Solutions-LLC/GVM-Docker#216] opened 2021-07-02 09:32 UTC
**Describe the bug**
After installing gvm image, and starting the container with "docker-compose up -d", scap-data and cert-data is not permitted. Moreover, the installation is frozen on "event config:MESSAGE:2021-07-02 11h16.34 utc:1150: Scan config Host Discovery (2d3f051c-55ba-11e3-bf43-406186ea4fc5) has been created by admin".

**Screenshots**
![image](https://user-images.githubusercontent.com/71044702/124253717-fdeccd80-db30-11eb-9e0b-58668d9261ea.png)

![image](https://user-images.githubusercontent.com/71044702/124253769-0a712600-db31-11eb-9236-28bcdb41a0bc.png)

![image](https://user-images.githubusercontent.com/71044702/124254081-6045ce00-db31-11eb-849e-db54cf56be8e.png)

![image](https://user-images.githubusercontent.com/71044702/124268001-a571fc00-db41-11eb-8168-11ff6d8d8dde.png)

Best Regards,

Imad Boustany,
Security Operations engineer.

**Comment by Dexus** [comment] 2021-07-02 18:32
Can you give me the SHA256 of your Image?

How did you start your Container? Direct Docker oder per Compose?

**Comment by imad777550** [comment] 2021-07-03 17:35
**I restarted the installation, It seems that the Permission error is gone but the installation is still frozen.**

**Screenshot:**

![image](https://user-images.githubusercontent.com/71044702/124362549-3deda680-dc3e-11eb-8c01-95be473b3a06.png)




**SHA256:** 0ca3978bd82fc0573d1ce9d04dc5595dc5053e72325472052863288e5eb6416b

**Docker-Compose:**

version: "3"
services:
    gvm:
        image: securecompliance/gvm
        volumes:
          - /home/usm/GVM-Docker/gvm-data:/data
        environment:
          - USERNAME="admin"
          - PASSWORD="admin"
          - RELAYHOST="smtp"
          - SMTPPORT=25
          - AUTO_SYNC=true
          - HTTPS=true
          - TZ="UTC"
          - SSHD=false
          - DB_PASSWORD="none"
        ports:
          - "8080:9392"  # Web interface

        restart: unless-stopped

**Comment by Dexus** [comment] 2021-07-03 19:24
Okay, let met ask you somethings:

- OS of the Server?
- output of `docker image inspect securecompliance/gvm` ID ?

As far I can see from the logs, everything is working as except form the current latest (21.4.0-V5) image.

I don't get what exactly you mean what is wrong. On all of my different systems it works. So please explain what you think is wrong. And maybe you are willing to build your own image from the dev branch and check if it works better for you.

**Comment by imad777550** [comment] 2021-07-04 12:09
![image](https://user-images.githubusercontent.com/71044702/124384128-97a2af00-dcd8-11eb-8485-260465991f83.png)

1 month ago, everything was okey. Now, the installation is stuck on "Scan config host discovery". I tried to pull the image on different clients servers with the same docker compose and the same result. I'm not able to identify the problem since there is no errors. Also, I downloaded the Dockerfile from Secure-Compliance repo and I build it but the same issue all the time. Can you please help me identifying the issue?

**Comment by Dexus** [comment] 2021-07-04 13:45
Hmm, can‘t say there is any bug or problem. I tried the latest version on many systems. Are you able to access the web ui? If so please check the NVTs.

If you get there a error that no scap data available. Wait for ~10 minutes an check again. If this is not working after 30 minutes, make a snapshot from the running container and please provide it as download, then I can have a look what maybe is broken. Or you provide the full logs from the log directories. 

Von meinem iPhone gesendet

**Comment by Dexus** [comment] 2021-07-04 17:31
```
event config:MESSAGE:2021-07-03 19h35.44 utc:1556: Scan config EulerOS Linux Security Configuration (9f822ad3-9208-4e02-ac03-78dce3ca9a23) has been created by admin
event config:MESSAGE:2021-07-03 19h35.44 utc:1556: Scan config System Discovery (bbca7412-a950-11e3-9109-406186ea4fc5) has been created by admin
event config:MESSAGE:2021-07-03 19h35.44 utc:1556: Scan config Base (d21f6c81-2b88-4ac1-b7b4-a2a9f2ad4663) has been created by admin
event config:MESSAGE:2021-07-03 19h35.44 utc:1556: Scan config Host Discovery (2d3f051c-55ba-11e3-bf43-406186ea4fc5) has been created by admin
event config:MESSAGE:2021-07-03 19h35.45 utc:1556: Scan config GaussDB Kernel V500R001C00 Security Hardening Guide (2eec8313-fee4-442a-b3c4-fa0d5dc83d61) has been created by admin
event config:MESSAGE:2021-07-03 19h35.45 utc:1556: Scan config empty (085569ce-73ed-11df-83c3-002264764cea) has been created by admin
event config:MESSAGE:2021-07-03 19h35.46 utc:1556: Scan config IT-Grundschutz Kompendium (c4b7c0cb-6502-4809-b034-8e635311b3e6) has been created by admin
event config:MESSAGE:2021-07-03 19h35.47 utc:1556: Scan config Full and fast (daba56c8-73ec-11df-a475-002264764cea) has been created by admin
event config:MESSAGE:2021-07-03 19h35.47 utc:1556: Scan config Discovery (8715c877-47a0-438d-98a3-27c7a6ab2196) has been created by admin
event config:MESSAGE:2021-07-03 19h35.48 utc:1556: Scan config GaussDB 100 V300R001C00 Security Hardening Guide (Standalone) (61327f09-8a54-4854-9e1c-16798285fb28) has been created by admin
```

This is the output, and the container works for me, so this is not a bug in my eyes. I will close this issue, if you think it's a bug or you have other thoughts, feel free to reopen the issue.

**Closed by Dexus** 2021-07-04 17:31 UTC
Labels: bug
