### ISSUE TITLE
"Consider Alive"

### ISSUE THREAD

**Issue by madasus** [Secure-Compliance-Solutions-LLC/GVM-Docker#19] opened 2020-05-10 13:29 UTC
Hi All,

Is anyone having issues with the consider-alive option? I am using the CE version in a VM and the "consider-alive" option seems to work and detects everything correctly.

When using this version consider-alive doesn't appear to do anything.  I have hosts that do not respond to ping but have HTTPS running that are not detected when using

"All IANA assigned TCP and UDP 2012-02-10" (the same as on the VM version).

Any thoughts? something unique to docker?

**Comment by pixelsquared** [comment] 2020-05-13 21:32
Hi,
I am not able to reproduce the behavior you are describing. Do you have anymore information that could help reproduce the issue?

**Comment by madasus** [comment] 2020-05-14 00:22
If you create a target with one ip

Port list: "All IANA assigned TCP and UDP 2012-02-10" 
Alive Test: consider alive

Then create a new scan using that target with

Scanner: OpenVAS Default
Scan Config: Full and very deep ultimate
Max NVTs per host: 10
Max hosts: 20

Then just make sure that the host has 443 open but blocks ICMP (ping).  The scan will come back and say zero hosts found.

Same exact scan settings running in the CE virtual appliance shows the host with the open ports.

I can provide you a couple of ips privately if you need some to test with.

**Comment by beastie29a** [comment] 2020-05-14 05:54
> Hi All,
> 
> Is anyone having issues with the consider-alive option? I am using the CE version in a VM and the "consider-alive" option seems to work and detects everything correctly.
> 
> When using this version consider-alive doesn't appear to do anything. I have hosts that do not respond to ping but have HTTPS running that are not detected when using
> 
> "All IANA assigned TCP and UDP 2012-02-10" (the same as on the VM version).
> 
> Any thoughts? something unique to docker?

Yeah, I had this issue when the 9.0.0 release version was being compiled. The fix was created after that version in this commit:
https://github.com/greenbone/gvmd/commit/5dd6cf3730cef08ed63599cf9f79291f82ecda72

I ended up changing the build script to pull from the 9.0 branch instead so the commit would be included. Looks like the latest version of this build is based off the latest 9.0.1 release so upgrading should fix this issue.

**Comment by madasus** [comment] 2020-05-14 14:38
Perfect - I updated the docker to pick up the 9.0.1 change that was made last night and now the function works correctly.  Thank you so much!

**Comment by pixelsquared** [comment] 2020-05-15 05:24
Thank you @beastie29a for helping with this issue. It looks like this issue is resolved so I am closing this now.

**Closed by pixelsquared** 2020-05-15 05:24 UTC
