### ISSUE TITLE
[Bug] PDF reports are corrupt

### ISSUE THREAD

**Issue by huornlmj** [Secure-Compliance-Solutions-LLC/GVM-Docker#327] opened 2022-01-12 18:15 UTC
Version 21.4.2.  Reports download as PDF format are zero bytes in size.

**Comment by Dexus** [comment] 2022-03-04 10:50
duplicate of #249 

fix: https://github.com/Secure-Compliance-Solutions-LLC/GVM-Docker/issues/249#issuecomment-894805814

problem is the build host has to less memory so it fails.

**Closed by Dexus** 2022-03-04 10:50 UTC
Labels: bug

**Comment by Dexus** [comment] 2022-03-14 12:05
You can now use the https://hub.docker.com/r/deineagenturug/gvm images, which are using the latest gvmd and components releases.

It use POSTGRESQL 13. 

What are meaning the tags:

```
docker pull deineagenturug/gvm:latest               # is an not initialized basic image, that first start its initialization on the first start (short: no db & no PDF report support)
docker pull deineagenturug/gvm:latest-full          # is an not initialized basic image, that first start its initialization on the first start (short: no db, PDF report is support)
docker pull deineagenturug/gvm:latest-data          # is an initialized basic image, that can run directly without extra VOLUMES added (short: included db, but no PDF report support)
docker pull deineagenturug/gvm:latest-data-full     # is an initialized basic image, that can run directly without extra VOLUMES added (short: included db & PDF report is support)
```

It can be used as direct replacement for the here provided image, with the same arguments on `docker run`. 

---

PDF support is always broken if the release is build on Github runners, because of limited memory. The releases of `deineagenturug/gvm` are build on dedicated servers with enough memory so it should no problem anymore.
