### ISSUE TITLE
[Bug] Docker fails to build with COPY failed: stat /var/lib/docker/tmp/docker-builder211072295/apk-build/target: no such file or directory

### ISSUE THREAD

**Issue by nestoru** [Secure-Compliance-Solutions-LLC/GVM-Docker#270] opened 2021-09-03 12:05 UTC
**Describe the bug**
Docker fails to build with COPY failed: stat /var/lib/docker/tmp/docker-builder211072295/apk-build/target: no such file or directory

This was working last time I checked three months ago.

**To Reproduce**
1. Run the below:
docker build . -t gvm

2. See error:
COPY failed: stat /var/lib/docker/tmp/docker-builder211072295/apk-build/target: no such file or directory

**Expected behavior**
The docker image should build.

**Host Device:**
 - OS: Ubuntu 
 - Version: 20.04.2 LTS

**Image in use:**
- Self build
- Output from `docker image inspect <image>` :
```
$ docker image inspect gvm
[]
Error: No such image: gvm
```

**Comment by Dexus** [comment] 2021-09-03 15:16
It’s not a bug, you need to download the artifact from the apk build repo.

Regards

Von meinem iPhone gesendet

**Comment by austinsonger** [comment] 2021-09-03 15:21
@Dexus can we make a note of this somewhere so it's obvious for users.

**Comment by Dexus** [comment] 2021-09-03 15:32
Sure after my vacation I will work on the Debian image and will also add the notes to the docs.

Von meinem iPhone gesendet

**Comment by nestoru** [comment] 2021-09-04 14:35
If I can have at least the list of commands to run to get the apk build repo artifact downloaded that will be great. I cloned https://github.com/Secure-Compliance-Solutions-LLC/GVM-APK-build.git and run the make command and got the below 
```
Successfully built e1eb521db1a8
Successfully tagged apk_builder:nurquiza
```
but I have no idea what to do next because I still do not see an apk-build directory which is needed by the Dockerfile in the GVM-Docker repo:
```
COPY apk-build/target/ /repo/
COPY apk-build/user.abuild/*.pub /etc/apk/keys/
```

**Comment by Dexus** [comment] 2021-09-04 15:41
Have a look to the action pipelines of the repo. Or clone it and run `make user.abuilder` and `make build`

Von meinem iPhone gesendet

**Comment by nestoru** [comment] 2021-09-04 16:51
`make build` was failing because the docker image is run in non interactive mode and yet asking the user to confirm where the encryption key should be placed. After adding -ti I started getting `mkdir: can't create directory '/target/community/': Permission denied` which I assume might be the result of some var missing. I decided not to build from sources and instead run from the published latest image for now. Will check back in the future once the documentation is amended:

```
docker run --detach --publish 8080:9392 --env PASSWORD="admin" --volume gvm-data:/data/gvm-data --name gvm securecompliance/gvm:latest-data-full
```

Thanks a lot for trying with me.

**Comment by austinsonger** [comment] 2021-09-04 17:10
@nestoru I've done some rearranging of the [documentation](https://securecompliance.gitbook.io/projects/) today and will adding more context this coming week.

**Comment by nestoru** [comment] 2021-09-04 17:53
@austinsonger appreciate it!

**Comment by austinsonger** [comment] 2021-11-20 22:35
Have switch to Debian. Closing this.

**Closed by austinsonger** 2021-11-20 22:35 UTC
Labels: bug

**Comment by nestoru** [comment] 2021-12-14 01:17
@austinsonger could you please share what you mean by "have switch to Debian"? I just tried to build the image as explained in the first post in this thread and got the same result. Every other interaction is still valid here. I believe we need step by step instructions about how to build the docker image. Happy to help on my end as needed.
